# Model arguments
model_name_or_path: LeoLM/leo-hessianai-13b
torch_dtype: auto

use_flash_attention_2: true
load_in_4bit: true

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# Data training arguments
dataset_mixer:
  florentgbelidji/oa_german: 1.0
dataset_splits:
- train_german
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: "no"
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: florentgbelidji/leoLM-13b-sft-lora-oa
save_strategy: steps
save_steps: 200
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 1024
max_steps: -1
num_train_epochs: 1
output_dir: data/leoLM-13b-sft-lora-oa
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
run_name: Test accelerate multi-gpu 2
report_to:
- wandb
save_strategy: "no"
save_total_limit: null
seed: 42